-- Препроцессинг для модели (specs/препроцессинг-для-модели.md).
-- Колонки признаков сгенерированы из src/common/feature_columns.py —
-- единственного источника правды для их имён и типов (при повторной
-- генерации, если список меняется, этот блок регенерируется тем же
-- способом, а не правится вручную построчно).

-- ДП-0: счёт основного времени. NULL для обычных FT-матчей (совпадает
-- с goals_home/away); заполняется для AET/PEN из score.fulltime.
ALTER TABLE fixtures ADD COLUMN ft90_home SMALLINT;
ALTER TABLE fixtures ADD COLUMN ft90_away SMALLINT;

COMMENT ON COLUMN fixtures.ft90_home IS
    'Счёт хозяев после 90 минут (score.fulltime). NULL у FT-матчей: там совпадает с goals_home. Заполняется у AET/PEN (ДП-0).';

-- ДП-11: витрина признаков для модели. Не VIEW — Эло (ДП-8) требует
-- последовательного прохода по истории, не выражается SQL-запросом.
CREATE TABLE ml_match_features (
    fixture_id INTEGER PRIMARY KEY REFERENCES fixtures (fixture_id) ON DELETE RESTRICT,
    computed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    league_id INTEGER,
    season INTEGER,
    match_date DATE,
    kickoff_at TIMESTAMPTZ,
    home_team_id INTEGER,
    away_team_id INTEGER,
    reg_home SMALLINT,
    reg_away SMALLINT,
    result_1x2 TEXT,
    league_total_line NUMERIC(5,2),
    league_total_over BOOLEAN,
    btts BOOLEAN,
    home_team_line NUMERIC(5,2),
    home_total_over BOOLEAN,
    away_team_line NUMERIC(5,2),
    away_total_over BOOLEAN,
    handicap_favorite TEXT,
    handicap_line NUMERIC(5,2),
    handicap_favorite_covers BOOLEAN,
    dc_1x BOOLEAN,
    dc_x2 BOOLEAN,
    dc_12 BOOLEAN,
    home_team_overall_short_goals_scored_avg NUMERIC(6,3),
    home_team_overall_short_goals_conceded_avg NUMERIC(6,3),
    home_team_overall_short_points_avg NUMERIC(6,3),
    home_team_overall_short_win_rate NUMERIC(6,3),
    home_team_overall_short_draw_rate NUMERIC(6,3),
    home_team_overall_short_loss_rate NUMERIC(6,3),
    home_team_overall_short_clean_sheet_rate NUMERIC(6,3),
    home_team_overall_short_failed_to_score_rate NUMERIC(6,3),
    home_team_overall_short_matches_played SMALLINT,
    home_team_overall_long_goals_scored_avg NUMERIC(6,3),
    home_team_overall_long_goals_conceded_avg NUMERIC(6,3),
    home_team_overall_long_points_avg NUMERIC(6,3),
    home_team_overall_long_win_rate NUMERIC(6,3),
    home_team_overall_long_draw_rate NUMERIC(6,3),
    home_team_overall_long_loss_rate NUMERIC(6,3),
    home_team_overall_long_clean_sheet_rate NUMERIC(6,3),
    home_team_overall_long_failed_to_score_rate NUMERIC(6,3),
    home_team_overall_long_matches_played SMALLINT,
    home_team_home_short_goals_scored_avg NUMERIC(6,3),
    home_team_home_short_goals_conceded_avg NUMERIC(6,3),
    home_team_home_short_points_avg NUMERIC(6,3),
    home_team_home_short_win_rate NUMERIC(6,3),
    home_team_home_short_draw_rate NUMERIC(6,3),
    home_team_home_short_loss_rate NUMERIC(6,3),
    home_team_home_short_clean_sheet_rate NUMERIC(6,3),
    home_team_home_short_failed_to_score_rate NUMERIC(6,3),
    home_team_home_short_matches_played SMALLINT,
    home_team_home_long_goals_scored_avg NUMERIC(6,3),
    home_team_home_long_goals_conceded_avg NUMERIC(6,3),
    home_team_home_long_points_avg NUMERIC(6,3),
    home_team_home_long_win_rate NUMERIC(6,3),
    home_team_home_long_draw_rate NUMERIC(6,3),
    home_team_home_long_loss_rate NUMERIC(6,3),
    home_team_home_long_clean_sheet_rate NUMERIC(6,3),
    home_team_home_long_failed_to_score_rate NUMERIC(6,3),
    home_team_home_long_matches_played SMALLINT,
    home_team_away_short_goals_scored_avg NUMERIC(6,3),
    home_team_away_short_goals_conceded_avg NUMERIC(6,3),
    home_team_away_short_points_avg NUMERIC(6,3),
    home_team_away_short_win_rate NUMERIC(6,3),
    home_team_away_short_draw_rate NUMERIC(6,3),
    home_team_away_short_loss_rate NUMERIC(6,3),
    home_team_away_short_clean_sheet_rate NUMERIC(6,3),
    home_team_away_short_failed_to_score_rate NUMERIC(6,3),
    home_team_away_short_matches_played SMALLINT,
    home_team_away_long_goals_scored_avg NUMERIC(6,3),
    home_team_away_long_goals_conceded_avg NUMERIC(6,3),
    home_team_away_long_points_avg NUMERIC(6,3),
    home_team_away_long_win_rate NUMERIC(6,3),
    home_team_away_long_draw_rate NUMERIC(6,3),
    home_team_away_long_loss_rate NUMERIC(6,3),
    home_team_away_long_clean_sheet_rate NUMERIC(6,3),
    home_team_away_long_failed_to_score_rate NUMERIC(6,3),
    home_team_away_long_matches_played SMALLINT,
    away_team_overall_short_goals_scored_avg NUMERIC(6,3),
    away_team_overall_short_goals_conceded_avg NUMERIC(6,3),
    away_team_overall_short_points_avg NUMERIC(6,3),
    away_team_overall_short_win_rate NUMERIC(6,3),
    away_team_overall_short_draw_rate NUMERIC(6,3),
    away_team_overall_short_loss_rate NUMERIC(6,3),
    away_team_overall_short_clean_sheet_rate NUMERIC(6,3),
    away_team_overall_short_failed_to_score_rate NUMERIC(6,3),
    away_team_overall_short_matches_played SMALLINT,
    away_team_overall_long_goals_scored_avg NUMERIC(6,3),
    away_team_overall_long_goals_conceded_avg NUMERIC(6,3),
    away_team_overall_long_points_avg NUMERIC(6,3),
    away_team_overall_long_win_rate NUMERIC(6,3),
    away_team_overall_long_draw_rate NUMERIC(6,3),
    away_team_overall_long_loss_rate NUMERIC(6,3),
    away_team_overall_long_clean_sheet_rate NUMERIC(6,3),
    away_team_overall_long_failed_to_score_rate NUMERIC(6,3),
    away_team_overall_long_matches_played SMALLINT,
    away_team_home_short_goals_scored_avg NUMERIC(6,3),
    away_team_home_short_goals_conceded_avg NUMERIC(6,3),
    away_team_home_short_points_avg NUMERIC(6,3),
    away_team_home_short_win_rate NUMERIC(6,3),
    away_team_home_short_draw_rate NUMERIC(6,3),
    away_team_home_short_loss_rate NUMERIC(6,3),
    away_team_home_short_clean_sheet_rate NUMERIC(6,3),
    away_team_home_short_failed_to_score_rate NUMERIC(6,3),
    away_team_home_short_matches_played SMALLINT,
    away_team_home_long_goals_scored_avg NUMERIC(6,3),
    away_team_home_long_goals_conceded_avg NUMERIC(6,3),
    away_team_home_long_points_avg NUMERIC(6,3),
    away_team_home_long_win_rate NUMERIC(6,3),
    away_team_home_long_draw_rate NUMERIC(6,3),
    away_team_home_long_loss_rate NUMERIC(6,3),
    away_team_home_long_clean_sheet_rate NUMERIC(6,3),
    away_team_home_long_failed_to_score_rate NUMERIC(6,3),
    away_team_home_long_matches_played SMALLINT,
    away_team_away_short_goals_scored_avg NUMERIC(6,3),
    away_team_away_short_goals_conceded_avg NUMERIC(6,3),
    away_team_away_short_points_avg NUMERIC(6,3),
    away_team_away_short_win_rate NUMERIC(6,3),
    away_team_away_short_draw_rate NUMERIC(6,3),
    away_team_away_short_loss_rate NUMERIC(6,3),
    away_team_away_short_clean_sheet_rate NUMERIC(6,3),
    away_team_away_short_failed_to_score_rate NUMERIC(6,3),
    away_team_away_short_matches_played SMALLINT,
    away_team_away_long_goals_scored_avg NUMERIC(6,3),
    away_team_away_long_goals_conceded_avg NUMERIC(6,3),
    away_team_away_long_points_avg NUMERIC(6,3),
    away_team_away_long_win_rate NUMERIC(6,3),
    away_team_away_long_draw_rate NUMERIC(6,3),
    away_team_away_long_loss_rate NUMERIC(6,3),
    away_team_away_long_clean_sheet_rate NUMERIC(6,3),
    away_team_away_long_failed_to_score_rate NUMERIC(6,3),
    away_team_away_long_matches_played SMALLINT,
    home_team_overall_short_stats_coverage NUMERIC(4,3),
    home_team_overall_short_shots_on_goal_for_avg NUMERIC(7,3),
    home_team_overall_short_shots_on_goal_against_avg NUMERIC(7,3),
    home_team_overall_short_total_shots_for_avg NUMERIC(7,3),
    home_team_overall_short_total_shots_against_avg NUMERIC(7,3),
    home_team_overall_short_corner_kicks_for_avg NUMERIC(7,3),
    home_team_overall_short_corner_kicks_against_avg NUMERIC(7,3),
    home_team_overall_short_ball_possession_for_avg NUMERIC(7,3),
    home_team_overall_short_ball_possession_against_avg NUMERIC(7,3),
    home_team_overall_short_expected_goals_for_avg NUMERIC(7,3),
    home_team_overall_short_expected_goals_against_avg NUMERIC(7,3),
    home_team_overall_long_stats_coverage NUMERIC(4,3),
    home_team_overall_long_shots_on_goal_for_avg NUMERIC(7,3),
    home_team_overall_long_shots_on_goal_against_avg NUMERIC(7,3),
    home_team_overall_long_total_shots_for_avg NUMERIC(7,3),
    home_team_overall_long_total_shots_against_avg NUMERIC(7,3),
    home_team_overall_long_corner_kicks_for_avg NUMERIC(7,3),
    home_team_overall_long_corner_kicks_against_avg NUMERIC(7,3),
    home_team_overall_long_ball_possession_for_avg NUMERIC(7,3),
    home_team_overall_long_ball_possession_against_avg NUMERIC(7,3),
    home_team_overall_long_expected_goals_for_avg NUMERIC(7,3),
    home_team_overall_long_expected_goals_against_avg NUMERIC(7,3),
    home_team_home_short_stats_coverage NUMERIC(4,3),
    home_team_home_short_shots_on_goal_for_avg NUMERIC(7,3),
    home_team_home_short_shots_on_goal_against_avg NUMERIC(7,3),
    home_team_home_short_total_shots_for_avg NUMERIC(7,3),
    home_team_home_short_total_shots_against_avg NUMERIC(7,3),
    home_team_home_short_corner_kicks_for_avg NUMERIC(7,3),
    home_team_home_short_corner_kicks_against_avg NUMERIC(7,3),
    home_team_home_short_ball_possession_for_avg NUMERIC(7,3),
    home_team_home_short_ball_possession_against_avg NUMERIC(7,3),
    home_team_home_short_expected_goals_for_avg NUMERIC(7,3),
    home_team_home_short_expected_goals_against_avg NUMERIC(7,3),
    home_team_home_long_stats_coverage NUMERIC(4,3),
    home_team_home_long_shots_on_goal_for_avg NUMERIC(7,3),
    home_team_home_long_shots_on_goal_against_avg NUMERIC(7,3),
    home_team_home_long_total_shots_for_avg NUMERIC(7,3),
    home_team_home_long_total_shots_against_avg NUMERIC(7,3),
    home_team_home_long_corner_kicks_for_avg NUMERIC(7,3),
    home_team_home_long_corner_kicks_against_avg NUMERIC(7,3),
    home_team_home_long_ball_possession_for_avg NUMERIC(7,3),
    home_team_home_long_ball_possession_against_avg NUMERIC(7,3),
    home_team_home_long_expected_goals_for_avg NUMERIC(7,3),
    home_team_home_long_expected_goals_against_avg NUMERIC(7,3),
    home_team_away_short_stats_coverage NUMERIC(4,3),
    home_team_away_short_shots_on_goal_for_avg NUMERIC(7,3),
    home_team_away_short_shots_on_goal_against_avg NUMERIC(7,3),
    home_team_away_short_total_shots_for_avg NUMERIC(7,3),
    home_team_away_short_total_shots_against_avg NUMERIC(7,3),
    home_team_away_short_corner_kicks_for_avg NUMERIC(7,3),
    home_team_away_short_corner_kicks_against_avg NUMERIC(7,3),
    home_team_away_short_ball_possession_for_avg NUMERIC(7,3),
    home_team_away_short_ball_possession_against_avg NUMERIC(7,3),
    home_team_away_short_expected_goals_for_avg NUMERIC(7,3),
    home_team_away_short_expected_goals_against_avg NUMERIC(7,3),
    home_team_away_long_stats_coverage NUMERIC(4,3),
    home_team_away_long_shots_on_goal_for_avg NUMERIC(7,3),
    home_team_away_long_shots_on_goal_against_avg NUMERIC(7,3),
    home_team_away_long_total_shots_for_avg NUMERIC(7,3),
    home_team_away_long_total_shots_against_avg NUMERIC(7,3),
    home_team_away_long_corner_kicks_for_avg NUMERIC(7,3),
    home_team_away_long_corner_kicks_against_avg NUMERIC(7,3),
    home_team_away_long_ball_possession_for_avg NUMERIC(7,3),
    home_team_away_long_ball_possession_against_avg NUMERIC(7,3),
    home_team_away_long_expected_goals_for_avg NUMERIC(7,3),
    home_team_away_long_expected_goals_against_avg NUMERIC(7,3),
    away_team_overall_short_stats_coverage NUMERIC(4,3),
    away_team_overall_short_shots_on_goal_for_avg NUMERIC(7,3),
    away_team_overall_short_shots_on_goal_against_avg NUMERIC(7,3),
    away_team_overall_short_total_shots_for_avg NUMERIC(7,3),
    away_team_overall_short_total_shots_against_avg NUMERIC(7,3),
    away_team_overall_short_corner_kicks_for_avg NUMERIC(7,3),
    away_team_overall_short_corner_kicks_against_avg NUMERIC(7,3),
    away_team_overall_short_ball_possession_for_avg NUMERIC(7,3),
    away_team_overall_short_ball_possession_against_avg NUMERIC(7,3),
    away_team_overall_short_expected_goals_for_avg NUMERIC(7,3),
    away_team_overall_short_expected_goals_against_avg NUMERIC(7,3),
    away_team_overall_long_stats_coverage NUMERIC(4,3),
    away_team_overall_long_shots_on_goal_for_avg NUMERIC(7,3),
    away_team_overall_long_shots_on_goal_against_avg NUMERIC(7,3),
    away_team_overall_long_total_shots_for_avg NUMERIC(7,3),
    away_team_overall_long_total_shots_against_avg NUMERIC(7,3),
    away_team_overall_long_corner_kicks_for_avg NUMERIC(7,3),
    away_team_overall_long_corner_kicks_against_avg NUMERIC(7,3),
    away_team_overall_long_ball_possession_for_avg NUMERIC(7,3),
    away_team_overall_long_ball_possession_against_avg NUMERIC(7,3),
    away_team_overall_long_expected_goals_for_avg NUMERIC(7,3),
    away_team_overall_long_expected_goals_against_avg NUMERIC(7,3),
    away_team_home_short_stats_coverage NUMERIC(4,3),
    away_team_home_short_shots_on_goal_for_avg NUMERIC(7,3),
    away_team_home_short_shots_on_goal_against_avg NUMERIC(7,3),
    away_team_home_short_total_shots_for_avg NUMERIC(7,3),
    away_team_home_short_total_shots_against_avg NUMERIC(7,3),
    away_team_home_short_corner_kicks_for_avg NUMERIC(7,3),
    away_team_home_short_corner_kicks_against_avg NUMERIC(7,3),
    away_team_home_short_ball_possession_for_avg NUMERIC(7,3),
    away_team_home_short_ball_possession_against_avg NUMERIC(7,3),
    away_team_home_short_expected_goals_for_avg NUMERIC(7,3),
    away_team_home_short_expected_goals_against_avg NUMERIC(7,3),
    away_team_home_long_stats_coverage NUMERIC(4,3),
    away_team_home_long_shots_on_goal_for_avg NUMERIC(7,3),
    away_team_home_long_shots_on_goal_against_avg NUMERIC(7,3),
    away_team_home_long_total_shots_for_avg NUMERIC(7,3),
    away_team_home_long_total_shots_against_avg NUMERIC(7,3),
    away_team_home_long_corner_kicks_for_avg NUMERIC(7,3),
    away_team_home_long_corner_kicks_against_avg NUMERIC(7,3),
    away_team_home_long_ball_possession_for_avg NUMERIC(7,3),
    away_team_home_long_ball_possession_against_avg NUMERIC(7,3),
    away_team_home_long_expected_goals_for_avg NUMERIC(7,3),
    away_team_home_long_expected_goals_against_avg NUMERIC(7,3),
    away_team_away_short_stats_coverage NUMERIC(4,3),
    away_team_away_short_shots_on_goal_for_avg NUMERIC(7,3),
    away_team_away_short_shots_on_goal_against_avg NUMERIC(7,3),
    away_team_away_short_total_shots_for_avg NUMERIC(7,3),
    away_team_away_short_total_shots_against_avg NUMERIC(7,3),
    away_team_away_short_corner_kicks_for_avg NUMERIC(7,3),
    away_team_away_short_corner_kicks_against_avg NUMERIC(7,3),
    away_team_away_short_ball_possession_for_avg NUMERIC(7,3),
    away_team_away_short_ball_possession_against_avg NUMERIC(7,3),
    away_team_away_short_expected_goals_for_avg NUMERIC(7,3),
    away_team_away_short_expected_goals_against_avg NUMERIC(7,3),
    away_team_away_long_stats_coverage NUMERIC(4,3),
    away_team_away_long_shots_on_goal_for_avg NUMERIC(7,3),
    away_team_away_long_shots_on_goal_against_avg NUMERIC(7,3),
    away_team_away_long_total_shots_for_avg NUMERIC(7,3),
    away_team_away_long_total_shots_against_avg NUMERIC(7,3),
    away_team_away_long_corner_kicks_for_avg NUMERIC(7,3),
    away_team_away_long_corner_kicks_against_avg NUMERIC(7,3),
    away_team_away_long_ball_possession_for_avg NUMERIC(7,3),
    away_team_away_long_ball_possession_against_avg NUMERIC(7,3),
    away_team_away_long_expected_goals_for_avg NUMERIC(7,3),
    away_team_away_long_expected_goals_against_avg NUMERIC(7,3),
    h2h_matches_played SMALLINT,
    h2h_avg_total_goals NUMERIC(5,2),
    h2h_home_team_win_rate NUMERIC(4,3),
    h2h_draw_rate NUMERIC(4,3),
    h2h_away_team_win_rate NUMERIC(4,3),
    injuries_home_count SMALLINT,
    injuries_away_count SMALLINT,
    league_home_win_rate NUMERIC(4,3),
    league_draw_rate NUMERIC(4,3),
    league_away_win_rate NUMERIC(4,3),
    home_team_rank SMALLINT,
    away_team_rank SMALLINT,
    home_team_points SMALLINT,
    away_team_points SMALLINT,
    points_gap SMALLINT,
    home_team_elo NUMERIC(7,2),
    away_team_elo NUMERIC(7,2),
    elo_diff NUMERIC(7,2),
    eval_1xbet_odds_home NUMERIC(8,3),
    eval_1xbet_odds_draw NUMERIC(8,3),
    eval_1xbet_odds_away NUMERIC(8,3),
    eval_1xbet_odds_btts_yes NUMERIC(8,3),
    eval_1xbet_odds_btts_no NUMERIC(8,3),
    eval_1xbet_odds_league_total_over NUMERIC(8,3),
    eval_1xbet_odds_league_total_under NUMERIC(8,3),
    eval_1xbet_odds_home_total_over NUMERIC(8,3),
    eval_1xbet_odds_home_total_under NUMERIC(8,3),
    eval_1xbet_odds_away_total_over NUMERIC(8,3),
    eval_1xbet_odds_away_total_under NUMERIC(8,3),
    eval_1xbet_odds_handicap_favorite NUMERIC(8,3),
    eval_1xbet_odds_dc_1x NUMERIC(8,3),
    eval_1xbet_odds_dc_x2 NUMERIC(8,3),
    eval_1xbet_odds_dc_12 NUMERIC(8,3),
    eval_pinnacle_odds_home NUMERIC(8,3),
    eval_pinnacle_odds_draw NUMERIC(8,3),
    eval_pinnacle_odds_away NUMERIC(8,3),
    eval_pinnacle_odds_btts_yes NUMERIC(8,3),
    eval_pinnacle_odds_btts_no NUMERIC(8,3),
    eval_pinnacle_odds_league_total_over NUMERIC(8,3),
    eval_pinnacle_odds_league_total_under NUMERIC(8,3),
    eval_pinnacle_odds_home_total_over NUMERIC(8,3),
    eval_pinnacle_odds_home_total_under NUMERIC(8,3),
    eval_pinnacle_odds_away_total_over NUMERIC(8,3),
    eval_pinnacle_odds_away_total_under NUMERIC(8,3),
    eval_pinnacle_odds_handicap_favorite NUMERIC(8,3),
    eval_pinnacle_odds_dc_1x NUMERIC(8,3),
    eval_pinnacle_odds_dc_x2 NUMERIC(8,3),
    eval_pinnacle_odds_dc_12 NUMERIC(8,3)
);

COMMENT ON TABLE ml_match_features IS
    'Одна строка — один матч с известным результатом. Признаки и цели для модели (specs/препроцессинг-для-модели.md). Наполняется src/jobs/build_features.py.';

CREATE INDEX idx_ml_features_league_season ON ml_match_features (league_id, season);
CREATE INDEX idx_ml_features_match_date ON ml_match_features (match_date);

-- ДП-8: состояние рейтинга Эло между запусками build_features.py.
-- Без него инкрементальный пересчёт не мог бы продолжить рейтинг без
-- повторного прохода по всей истории.
CREATE TABLE ml_team_elo_state (
    team_id INTEGER NOT NULL,
    league_id INTEGER NOT NULL REFERENCES leagues (league_id) ON DELETE RESTRICT,
    rating NUMERIC(7, 2) NOT NULL,
    as_of_fixture_id INTEGER NOT NULL REFERENCES fixtures (fixture_id) ON DELETE RESTRICT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (team_id, league_id)
);

COMMENT ON TABLE ml_team_elo_state IS
    'Рейтинг Эло команды в лиге на момент последнего учтённого матча (ДП-8). Сквозной по сезонам, обновляется build_features.py.';
